# Form implementation generated from reading ui file 'añadir.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 329)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tabShare = QtWidgets.QWidget()
        self.tabShare.setObjectName("tabShare")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabShare)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.tabShare)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.EdtPath = QtWidgets.QLineEdit(self.tabShare)
        self.EdtPath.setObjectName("EdtPath")
        self.horizontalLayout.addWidget(self.EdtPath)
        self.BtnExplorar = QtWidgets.QPushButton(self.tabShare)
        self.BtnExplorar.setObjectName("BtnExplorar")
        self.horizontalLayout.addWidget(self.BtnExplorar)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.EdtName = QtWidgets.QLineEdit(self.tabShare)
        self.EdtName.setObjectName("EdtName")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.EdtName)
        self.chkWrite = QtWidgets.QCheckBox(self.tabShare)
        self.chkWrite.setObjectName("chkWrite")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chkWrite)
        self.chkBrowseable = QtWidgets.QCheckBox(self.tabShare)
        self.chkBrowseable.setObjectName("chkBrowseable")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chkBrowseable)
        self.label_2 = QtWidgets.QLabel(self.tabShare)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.tabShare, "")
        self.tabUsers = QtWidgets.QWidget()
        self.tabUsers.setObjectName("tabUsers")
        self.tabWidget.addTab(self.tabUsers, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnConfirmar = QtWidgets.QPushButton(Form)
        self.BtnConfirmar.setObjectName("BtnConfirmar")
        self.horizontalLayout_2.addWidget(self.BtnConfirmar)
        self.BtnCancelar = QtWidgets.QPushButton(Form)
        self.BtnCancelar.setObjectName("BtnCancelar")
        self.horizontalLayout_2.addWidget(self.BtnCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Añadir"))
        self.label.setText(_translate("Form", "Directorio"))
        self.BtnExplorar.setText(_translate("Form", "Explorar"))
        self.chkWrite.setText(_translate("Form", "Escritura"))
        self.chkBrowseable.setText(_translate("Form", "Visible"))
        self.label_2.setText(_translate("Form", "Nombre de recurso"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabShare), _translate("Form", "Recurso"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUsers), _translate("Form", "Usuarios"))
        self.BtnConfirmar.setText(_translate("Form", "Confirmar"))
        self.BtnCancelar.setText(_translate("Form", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
